JuliaMolSim/AtomsBase.jl

- .github/workflows/CI.yml
- .github/workflows/CompatHelper.yml
- .github/workflows/TagBot.yml
- Project.toml
This PR adds a few package related things:
- A GitHub Action to run the package tests on pushing to branches, and every week as a cron job. Our tests are currently minimal but even checking the package can load is something, and we may add more tests later.
- TagBot GitHub Action to make tagging releases easier.
- CompatHelper GitHub Action to check for updates in our dependencies. Compat bounds are added to Project.toml to allow this (which also makes package registration faster).
The registrator bot is also now active on the repo.
> GitHub Actions for autobuild, TagBot and CompatHelper

- Project.toml
- src/interface.jl
Having it there causes problems in downstream packages who have their own `show` methods but if they've only defined one of the `show` flavors and it gets invoked in REPL, it might fall back to this one, which is especially problematic if for any reason one of the interface functions it relies upon isn't dispatched...
> remove Base.show dispatch

- .github/workflows/TagBot.yml
As described in https://github.com/JuliaMolSim/AtomsBase.jl/pull/41 the docs build is not triggering when TagBot runs.
I have added the appropriate repo secrets so this should solve the problem.
> Fix docs deployment

- README.md
Signed-off-by: Rachel Kurchin <rkurchin@cmu.edu>
> add packages using AtomsBase

- src/fast_system.jl
- test/printing.jl
The tests for printing were not testing anything. I have used `repr` to test the `show` methods.
> `show` for `FastSystem` and improved tests

- docs/src/atomicsystems.md
Atom function was referred to as Atoms in documentation.
> Fix Atom() function call typo

- Project.toml
- docs/src/overview.md
- docs/src/tutorial.md
- src/atom.jl
- src/atomview.jl
- src/interface.jl
- test/atom.jl
- test/fast_system.jl
- test/interface.jl
In the current implementation the `getkey` function does something the `get` function ought to be doing (namely to return a property from an atom or system if it exists, otherwise return a default). This is contrast to the way `getkey` behaves in the rest of Julia. This PR fixes this and makes the `get` function behave properly.
> Rename getkey to get and fix it

- docs/src/apireference.md
- src/atomview.jl
- src/fast_system.jl
- src/flexible_system.jl
- test/fast_system.jl
- test/interface.jl
- test/printing.jl
Hi! Here is a proposal to simplify a little bit the definition of struct-of-array systems, like `FastSystem`.
Currently, the two following definitions are required for each property like `position`:
```julia
position(s::FastSystem) = s.position
position(s::FastSystem, i) = s.position[i]
```
Since they are quite redundant, I suggest not requiring the latter. Instead, a `position(system, i)` call would be intercepted by the already existing fallback
https://github.com/JuliaMolSim/AtomsBase.jl/blob/092756182c37a862989da88ebb3fea6c14154388/src/interface.jl#L100
which can be made to work simply by tweaking the definitions of `position(v::AtomView)`. The emitted code should be identical in the end.
Also add some documentation for `AtomView` (since it is already exported and mentioned in the …
> Make AtomView rely on struct-of-array format

- src/fast_system.jl
- src/flexible_system.jl
- src/interface.jl
- test/atom.jl
- test/fast_system.jl
Now with the key-based property interface we can do `system[:, :property]` to get the corresponding `:property` for all atoms. Wouldn't it also make sense to support `system[rng, :property]` for a subset, `rng` of atom indices. Also, from the discussion in #29, I think returning a list of particle objects for slicing is more intuitive and useful. In this PR, I have implemented both of these, i.e., returning vector of particles objects on slicing AbstractSystems and the corresponding extension to the key-based property interface.
For example, with this, we can do `system[atomic_symbol(system) .== :H]` to get all H atoms.
I am just putting this here as a working version to show the usefulness of this feature. Feel free to close this in case we think slicing need not be supported.
> Slicing support

- .github/dependabot.yml
- .github/workflows/CI.yml
- .gitignore
- Project.toml
- docs/make.jl
- docs/src/testing.md
- lib/AtomsBaseTesting/LICENSE
- lib/AtomsBaseTesting/Project.toml
- lib/AtomsBaseTesting/src/AtomsBaseTesting.jl
- lib/AtomsBaseTesting/test/runtests.jl
- lib/AtomsBaseTesting/test/testmacros.jl
- test/runtests.jl
Adds a small subpackage, which can generate standard test cases and test equality between AtomsBase systems. Already used in ExtXYZ, [AtomsIO](https://github.com/mfherbst/AtomsIO.jl/blob/master/test/common.jl) and [ASEconnect](https://github.com/mfherbst/ASEconvert.jl/blob/master/test/common.jl) for testing (with code duplicated across these three packages). Clearly this has broader use, so this will allow registering a separate `AtomsBaseTesting` package.
> Add AtomsBaseTesting subpackage

- Project.toml
- docs/src/apireference.md
- src/AtomsBase.jl
- src/ascii_structure.jl
- src/show.jl
- src/visualize_ascii.jl
- test/printing.jl
The plain-text style representation is inspired by GPAW, the html style is basically @jgreener64's Bio3DView wrapped via [AtomsView](https://github.com/mfherbst/AtomsView.jl) (registration in progress).
What do people think: Do we want both the coordinates and the pictorial representation in the default plain-text `show` output or do we want to get rid of 
https://github.com/JuliaMolSim/AtomsBase.jl/blob/b336f845a8b25c1402ec1e9d20d3198f77dbc1db/src/show.jl#L59--L65
and thus only show the pictorial representation?
> Add plain-text and html-style graphical representation of structures to AtomsBase

- lib/AtomsBaseTesting/src/AtomsBaseTesting.jl
- lib/AtomsBaseTesting/test/runtests.jl
Added option `:diagonal` to AtomsBaseTesting `test_approx_equal`. The current options are not compatible with Molly.jl (triclinic & DirichletZero) and I would like to test against a valid system.
Also is `DirhichletZero` supposed to be a hard wall or infinite domain or something else?  Doesn't really make a difference for Molly but its not really clear from docs and not something I've ever seen in a molecular simulation context.
> Add :diagonal option to test_approx_equal

- docs/src/apireference.md
- src/properties.jl
- test/printing.jl
- test/properties.jl
... in particular for cases where atomic symbols don't agree with the element type.
> Improve chemical formula

- README.md
Hi,
I recently added an [extension to AutoBZCore.jl](https://github.com/lxvm/AutoBZCore.jl/blob/main/ext/AtomsBaseExt.jl) to interface with AtomsBase.jl systems. I thought adding the package to the readme would help improve visibility if it seems appropriate.
Cheers,
Lorenzo
> add AutoBZCore to readme

- lib/AtomsBaseTesting/src/AtomsBaseTesting.jl
- lib/AtomsBaseTesting/test/runtests.jl
> Fix testing of isolated systems

- lib/AtomsBaseTesting/Project.toml
- lib/AtomsBaseTesting/src/AtomsBaseTesting.jl
- lib/AtomsBaseTesting/test/runtests.jl
- src/AtomsBase.jl
- src/implementation/atom.jl
- src/implementation/fast_system.jl
- src/implementation/flexible_system.jl
- src/implementation/utils.jl
- src/interface.jl
- src/utils/atomview.jl
- src/utils/cells.jl
- src/utils/chemspecies.jl
- src/utils/show.jl
- src/utils/visualize_ascii.jl
- test/atom.jl
- test/fast_system.jl
- test/flexible_system.jl
- test/making_system.jl
- test/runtests.jl
- Reintroduce some previously disabled test
- Various smaller fixes to AtomsBase
- Fixes to AtomsBaseTesting
@cortner @rkurchin Could some of you take a quick look ?
> Extend AtomsBaseTesting and AtomsBase test routines

- Project.toml
- docs/src/apireference.md
- docs/src/interface.md
- docs/src/tutorial.md
- lib/AtomsBaseTesting/Project.toml
- lib/AtomsBaseTesting/src/AtomsBaseTesting.jl
- lib/AtomsBaseTesting/test/runtests.jl
- src/implementation/fast_system.jl
- src/implementation/flexible_system.jl
- src/implementation/utils.jl
- src/interface.jl
- src/utils/atomview.jl
- src/utils/cells.jl
- src/utils/show.jl
- src/utils/visualize_ascii.jl
- test/fast_system.jl
- test/flexible_system.jl
- test/interface.jl
- test/making_system.jl
- test/printing.jl
- test/test_docstrings.jl
Renamed occurrences of cell_vectors to bounding_box for consistency.
> Rename bounding_box to cell_vectors consistently

- .github/workflows/CI.yml
- Project.toml
- ext/AtomsBaseAtomsViewExt.jl
- src/AtomsBase.jl
- src/implementation/atom.jl
- src/utils/show.jl
- test/printing.jl
Follow-up to #121 to discuss ascii visualisation preferences. Ping @cortner @rkurchin @jgreener64 to get some opinions.
I personally find it quite convenient to automatically get this insight when working in the REPL or a notebook, but this may just be me. I also found it helps students ... but again I introduced it, so I'm biased.
Options in my opinion are:
- Don't do it, people have to do it by calling `visualize_ascii` manually each time. Pros: Clear what happens, least complexity; Cons: It's an extra function to learn for something where Julia has builtin mechanics.
- Use some preference to configure it, e.g. Just enable/disable, some threshold in terms of number of atoms (done right now) or some threshold in terms of "density" of atoms on the canvas (to avoid cluttered ascii art, …
> Introduce preference for automatic ascii visualization of system

- lib/AtomsBaseTesting/Project.toml
- lib/AtomsBaseTesting/src/AtomsBaseTesting.jl
Testing the cell vectors are equal can give `NaN` if `Inf` is used in non-periodic dimensions. This avoids checking non-periodic dimensions.
> AtomsBaseTesting cell vectors check for infinite systems

- docs/src/tutorial.md
A link to the DFTK documentation was broken.
> Fix link in tutorial.md

- src/utils/chemspecies.jl
- test/species.jl
Currently this will fail
```julia
using AtomsBase
using Unitful
hydrogen = isolated_system([
:H => [0, 0, 0.]u"Å",
:H => [0, 0, 1.]u"Å"
])
element_symbol(hydrogen, 1)  # error
```
This PR fixes it.
> Fix bug in element_symbol call

- src/utils/chemspecies.jl
- src/utils/properties.jl
- test/properties.jl
- test/species.jl
Mostly bug fixes, main thing to discuss:
I'm not sure having `chemical_formula` not return isotope-specific symbols is the right thing to do. If I have non-standard isotope compositions I would annotate it in a formula, so I make this change (see tests).
Thoughts about that ? @cortner made the current implementation I believe.
> Bugfixes related to chemical_formula
